
Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
	
	config.vm.box = "mwrock/Windows2016"
  
	config.vm.hostname = "WS2016"
#		test.vm.synced_folder "C:/vagrant/share", "C:/Users/vagrant/Desktop"
#		test.vm.provision "shell", inline: $script
	
	config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", inline: <<-SHELL

##Install Chokolatey:
#	Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
	get-windowsfeature
	Active Directory Domain Services: # чёт явно не то... необходимо выбрать вручную
	install-windowsfeature AD-Domain-Services	# Install-windowsfeature AD-domain-services
	
	Install-ADDSForest
	-CreateDnsDelegation:$false
	-DatabasePath "C:\Windows\NTDS"
	-DomainMode "Win2012R2"
	-DomainName "office.local"
	-DomainNetbiosName "OFFICE"
	-ForestMode "Win2012R2"
	-InstallDns:$true
	-LogPath "C:\Windows\NTDS"
	-NoRebootOnCompletion:$false
	-SysvolPath "C:\Windows\SYSVOL"
	-Force:$true
	
	
	SHELL
  
 ### Ну тип  и всё....
  

end
